### ISSUE TITLE
互联网热榜能提供RSS么？

### ISSUE THREAD

**Issue by scetus** [telami/hot#1]
喜欢把内容都通过一个地方来阅读。所以希望能提供一个RSS，这样我可以用inoreader来阅读。

如果能够提供，就太感谢了！

**Comment by telami** [comment]
> 喜欢把内容都通过一个地方来阅读。所以希望能提供一个RSS，这样我可以用inoreader来阅读。
> 
> 如果能够提供，就太感谢了！

周末我看一下，尽量提供

**Comment by scetus** [comment]
你好，我看这个讨论关闭了。是已经提供rss了么~~~我在页面上检索不到

**Comment by telami** [comment]
> 你好，我看这个讨论关闭了。是已经提供rss了么~~~我在页面上检索不到

不好意思，最近太忙了，就没弄
